# Generated by Django 4.2.1 on 2023-06-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics')),
                ('person', models.CharField(max_length=250)),
                ('designation', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
        ),
    ]
